version: '2'
services:
  sugarpp:
    extends:
      file: common.yml
      service: sugarapp_php56
    image: sugarsmith/sugarcontainer
    environment:
      - constraint:node==master
    depends_on:
      - mysql
    networks:
      - sugarnet

  mysql:
    extends:
      file: common.yml
      service: mysql
    networks:
      - sugarnet

  elasticsearch:
    extends:
      file: common.yml
      service: elasticsearch
    networks:
      - sugarnet


networks:
  sugarnet:
    driver: overlay
