version: '2'
services:
  sugarapp:
    extends:
      file: common.yml
      service: sugarapp
    #image: sugarsmith/sugarcontainer_php56
    image: php:7.1-apache
    environment:
      - constraint:node==master
    depends_on:
      - mysql
    networks:
      - sugarnet

  mysql:
    extends:
      file: common.yml
      service: mysql
    networks:
      - sugarnet

  elasticsearch:
    extends:
      file: common.yml
      service: elasticsearch
    networks:
      - sugarnet


networks:
  sugarnet:
    driver: bridge
