version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: sugarapp
    image: sugarsmith/sugarcontainer
    environment:
      - constraint:node==master
    depends_on:
      - mysql
    networks:
      - sugarnet

  mysql:
    extends:
      file: common.yml
      service: mysql
    networks:
      - sugarnet

networks:
  sugarnet:
    driver: overlay
